<?php
$nombres=Array("JAVIER MARTIN CASTRO",
"JAVIER RODRIGUEZ SOLER",
"JAVIER SEGARRA MARTINEZ",
"VICTOR DE VICENTE AÑON",
"VICTOR GUIJARRO PENALBA",
"ALBERTO CRIADO ANDRES",
"ALVARO GASCO VILLANOVA",
"ALVARO HERNANDEZ JIMENEZ DE LOS GALANES",
"BORJA RIBES CABALLERO",
"CARLES CHOVI ESTARELLES",
"DAVID FLORES PADILLA ",
"DOMINGO DE GUZMAN DE AROZARENA BARBERO",
"EMILIO JOSE HERAS FAJARDO",
"FRANCISCO PEREZ PASTOR",
"HECTOR JUAN SORIA",
"JOSEP SALVADOR CHANZA DOMINGO",
"JORDI XAVEIR PASTOR ALONSO",
"JONATHAN ROMERO MIRALLES",
"MIQUEL MARIN GARCIA",
"RAUL COMPANY BRAVO",
"RAFAEL JAREÑO PICAZO",
"RICARDO BOLUDA HERNANDEZ",
"SAMUEL MOLINER REIG");
echo "DELEGADO:".$nombres[rand(1,23)]."<br>";
echo "SUBDELEGADO:".$nombres[rand(1,23)];
?>